version: "3.8"
services:
  app:
    container_name: "crud-spring"
    build: .
    ports:
      - "8080"
    environment:
      - DATABASE_URL=jdbc:oracle:thin:@oracle-db:1521/free
      - DATABASE_USERNAME=system
      - DATABASE_PASSWORD=12345
    depends_on:
      - oracle-db

  oracle-db:
    container_name: "oracle-db"
    image: "container-registry.oracle.com/database/free"
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=12345

volumes:
  oracle-data:
